version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Run Client Tests
          working_directory: ~/repo/Client
          command: echo "Client tests pass!"
      - run:
          name: Run Backend Tests
          working_directory: ~/repo/Backend
          command: echo "Backend tests pass!"
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Client Dependencies
          working_directory: ~/repo/Client
          command: npm install
      - run:
          name: Build and upload to s3
          working_directory: ~/repo/Client
          command: npm run build
      - run:
          name: Install AWS CLI
          command: |
            sudo apt update
            sudo apt install awscli
      - run:
          name: Deploy Client to S3
          working_directory: ~/repo/Client
          command: |
            aws s3 cp ./build $S3_BUCKET_URL --recursive
      - run:
          name: Zip Backend
          working_directory: ~/repo/Backend
          command: zip -r Backend.zip .
      - run:
          name: Deploy Backend to Elastic Beanstalk
          command: |
            aws s3 cp my-app.zip $S3_FOR_BEANSTALK
            aws elasticbeanstalk create-application-version --application-name DevOpsSIA --version-label v1 --source-bundle S3Bucket="elasticbeanstalk-us-east-1-649177521606",S3Key="Backend.zip"
            aws elasticbeanstalk update-environment --application-name DevOpsSIA --environment-name DevOpsEnv --version-label v1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
