version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Run Client Tests
          working_directory: ~/repo/Client
          command: echo "Client tests pass!"
      - run:
          name: Run Backend Tests
          working_directory: ~/repo/Backend
          command: echo "Backend tests pass!"
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Client Dependencies
          working_directory: ~/repo/Client
          command: npm install
      - run:
          name: Build Client
          working_directory: ~/repo/Client
          command: npm run build
      - run:
          name: Install AWS CLI
          command: |
            sudo apt update
            sudo apt install awscli
            aws s3 ls

      - run:
          name: Deploy Client to S3
          working_directory: ~/repo/client
          command: |
            aws s3 cp ./build $S3_BUCKET_URL --recursive
      - run:
          name: Zip Backend
          working_directory: ~/repo/Backend
          command: zip -r Backend.zip .
      # - run:
      #     name: Deploy Backend to Elastic Beanstalk
      #     command: |
      #       aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      #       aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      #       aws configure set default.region $AWS_REGION
      #       aws elasticbeanstalk create-application-version --application-name my-app --version-label my-version --source-bundle S3Bucket="bucket-name",S3Key="backend.zip"
      #       aws elasticbeanstalk update-environment --environment-name my-env --version-label my-version

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
